# Generated by Django 5.2 on 2025-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionProfile',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('stress_level', models.IntegerField()),
                ('main_emotion', models.CharField(choices=[('relax', 'Расслабление'), ('happy', 'Радость'), ('sad', 'Грусть')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
